- hosts: all
  become: true
  tasks: 
    - name: delete old deployment
      command: kubectl delete -f /home/centos/Deployment.yml
    - name: delete old service
      command: kubectl delete -f /home/centos/Service.yml
    - name: create new deployment
      command: kubectl apply -f /home/centos/Deployment.yml
    - name: create new service
      command: kubectl apply -f /home/centos/Service.yml