kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops-project
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: devops-project
          image: goti03/devops-project 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
